# Generated by Django 4.2 on 2023-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
