# Generated by Django 4.2 on 2023-04-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Раздел'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэги'},
        ),
    ]
