# Generated by Django 3.1.2 on 2023-03-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_phone', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=100)),
                ('release_data', models.DateField()),
                ('lte_exists', models.BooleanField()),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
    ]
