# Generated by Django 4.2 on 2023-04-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_id_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='dt_measurement',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
