# Generated by Django 4.2 on 2023-04-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_dt_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='temp',
            field=models.FloatField(),
        ),
    ]
