# Generated by Django 4.2 on 2023-04-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_rename_id_sensor_measurement_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='temp',
            new_name='temperature',
        ),
    ]
