# Generated by Django 4.2 on 2023-04-29 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_rename_temp_measurement_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='dt_measurement',
            new_name='created_at',
        ),
    ]
